services:
  - type: web
    name: blitzapp
    env: node
    plan: free
    buildCommand: pnpm install && blitz build
    startCommand: blitz start -p ${PORT}
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true
